; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; --- Setup Section: Metadados do Instalador ---
[Setup]
; Nome da aplicação que aparecerá no Menu Iniciar e no Painel de Controle
AppName=Estoque Max
AppVersion=1.7.4
; Nome do Executável gerado (o instalador final)
OutputBaseFilename=Estoque_Max_Setup
; Diretório onde o instalador final será salvo, dentro do seu projeto
OutputDir=C:\AQUI
; O diretório de instalação padrão ({autopf} é Program Files no SO)
DefaultDirName={autopf}\Estoque Max
DefaultGroupName=Estoque Max
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Idioma do instalador
AppPublisher=Paulo Neto | EstoqueMax v1.7.4
UninstallDisplayIcon={app}\estoqueMax.exe
SourceDir=C:\Users\Teste\Desktop\ESTOQUE-MAX\estoqueMax

; --- Files Section: Quais arquivos incluir ---
[Files]
; 1. Inclui o Executável principal: estoqueMax.exe
; Source: Pega o arquivo dentro da pasta 'dist'
; DestDir: Coloca na pasta raiz da instalação ({app})
Source: "dist\estoqueMax.exe"; DestDir: "{app}"; Flags: ignoreversion

; --- Icons Section: Criando Atalhos ---
[Icons]
; 1. Atalho no Menu Iniciar
Name: "{group}\Estoque Max"; Filename: "{app}\estoqueMax.exe"
; 2. Atalho na Área de Trabalho (Desktop)
Name: "{autodesktop}\Estoque Max"; Filename: "{app}\estoqueMax.exe"